---
title: "<span style='color:#3498db;'>EDA Report</span> <br> <small style='font-size:0.6em; color:#7f8c8d;'>Model_Explanatory_Analysis</small>"
author: "<i class='fas fa-user'></i> **Metodi Latinov**"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: cosmo
    highlight: tango
    css: styles.css
params:
  random_forest: NULL 
  mars: NULL
  xgb: NULL
  glm_net: NULL
  linear_svm: NULL
knit: targets::tar_knit  
---

```{r setup, include=FALSE}

# Random Forest
random_forest_model <- params$random_forest$random_forest_fit
preproc_data_rf <- params$random_forest$preproc_data

# Mars
mars_model <- params$mars$mars_fit
preproc_data_mars <- params$mars$preproc_data

# XGB 
xgb_model <- params$xgb$xgb_fit
preproc_data_xgb <- params$xgb$preproc_data

# Glmnet
glm_net_model <- params$glm_net$glmnet_fit
preproc_data_glmnet <- params$glm_net$preproc_data

# Linear SVM
linear_svm_model <- params$linear_svm$svm_linear_fit
preproc_data_svm_l <- params$linear_svm$preproc_data

```

# Global Model Explanations 

```{r}

# Random Forest
rf_model_global <- global_explain(
  data = preproc_data_rf,
  model = random_forest_model,
  label = "Random Forest"
  )

# Mars
mars_model_global <- global_explain(
  data = preproc_data_mars,
  model = mars_model,
  label = "Mars"
  )

# Mars
xgb_model_global <- global_explain(
  data = preproc_data_xgb,
  model = xgb_model,
  label = "XGB"
  )

# Mars
glm_net_model_global <- global_explain(
  data = preproc_data_glmnet,
  model = glm_net_model,
  label = "Glmnet"
  )

# Linear_svm
linear_svm_model_global <- global_explain(
  data = preproc_data_svm_l,
  model = linear_svm_model,
  label = "Linear SVM"
  )
```

## Models Performace

### Random Forest

```{r}
rf_model_global$model_performance_plot
```

### MARS

```{r}
mars_model_global$model_performance_plot
```

### XGB

```{r}
xgb_model_global$model_performance_plot
```

### Glmnet

```{r}
glm_net_model_global$model_performance_plot
```

### Linear SVM

```{r}
linear_svm_model_global$model_performance_plot
```
    
## Model Importance Plot

### Random Forest

```{r}
rf_model_global$importance_full_plot
```

### MARS

```{r}
mars_model_global$importance_full_plot
```

### XBG

```{r}
xgb_model_global$importance_full_plot
```

### Glmnet

```{r}
glm_net_model_global$importance_full_plot
```

### Linear SVM

```{r}
linear_svm_model_global$importance_full_plot
```

## PDP 

### Random Forest 

```{r}
pdp_loan_intent_rate_rf <- rf_model_eval$pdp_loan_intent_rate_plot
pdp_income_rate_rf <- rf_model_eval$pdp_income_plot
pdp_emp_lenght_rf <- rf_model_eval$pdp_emp_lenght_plot

pdp_rf <- pdp_loan_intent_rate_rf / (pdp_income_rate_rf + pdp_emp_lenght_rf) 
plot(pdp_rf)
```

## ALE

### Random Forest

```{r}
ale_loan_pct_income_plot_rf <- rf_model_eval$ale_loan_pct_income_plot
ale_age_plot_rf <- rf_model_eval$ale_age_plot

rf_ale_plot <- ale_loan_pct_income_plot_rf + ale_age_plot_rf

plot(rf_ale_plot)
```

# Local Model Explanations 

```{r}

# Instance high/low

# Sort by descending income %, then take top row
instance_high_pct_income <- preproc_data_rf %>%
  arrange(desc(loan_percent_income)) %>%
  head(1)

# Sort by ascending income %, then take top row
instance_low_pct_income <- preproc_data_rf %>%
  arrange(loan_percent_income) %>%
  head(1)

local_rf_pct_income_high <- local_explain(
  data = preproc_data_rf,
  model = random_forest_model,
  instance = instance_high_pct_income,
  label = "Random Forest")

local_rf_pct_income_low <- local_explain(
  data = preproc_data_rf,
  model = random_forest_model,
  instance = instance_low_pct_income,
  label = "Random Forest")

```

## Break Down Plots

### Random Forest

```{r}
bdp_pct_income_high_plot <- local_rf_pct_income_high$break_down_plot
bdp_pct_income_low_plot <- local_rf_pct_income_low$break_down_plot

bdp_pct_income_plot <- bdp_pct_income_high_plot / bdp_pct_income_low_plot

plot(bdp_pct_income_plot)
```

## SHAP 

### Random Forest

```{r}
shap_pct_income_high_plot <- local_rf_pct_income_high$shap_plot
shap_pct_income_low_plot <- local_rf_pct_income_low$shap_plot

shap_income_plot <- shap_pct_income_high_plot / shap_pct_income_low_plot
plot(shap_income_plot)
```



